package vm

import (
	"sort"
	"sync"
)

// The member data is generated by tools/genemoji into emoji_strings.go.

var rgiEmoji = sync.OnceValue(func() []string {
	seen := map[string]bool{}
	var all []string
	names := make([]string, 0, len(propertiesOfStrings))
	for name := range propertiesOfStrings {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		for _, s := range propertiesOfStrings[name] {
			if !seen[s] {
				seen[s] = true
				all = append(all, s)
			}
		}
	}
	return all
})

// PropertyOfStrings returns the members of the Unicode property of strings
// named name (ECMA-262 table "Binary Unicode properties of strings"), such as
// RGI_Emoji, and whether name is one. The name must match exactly: unlike
// character properties, these have no aliases. Only the v flag admits them.
//
// The returned slice is shared and must not be modified.
func PropertyOfStrings(name string) ([]string, bool) {
	if name == "RGI_Emoji" {
		return rgiEmoji(), true
	}
	members, ok := propertiesOfStrings[name]
	return members, ok
}

// emojiProperty returns the membership test for an emoji binary property.
func emojiProperty(name string) func(rune) bool {
	ranges, ok := emojiProperties[name]
	if !ok {
		panic("vm: no emoji property " + name)
	}
	return func(r rune) bool { return inRanges(ranges, r) }
}
