package ecma262_test

import (
	"testing"

	"github.com/mgilbir/goecma262"
	"github.com/mgilbir/goecma262/flags"
)

// Case-insensitive matching of escapes, whose expectations were taken from
// node (V8, Unicode 17.0). Under u or v with i, ECMA-262 matches a rune
// against a set by comparing simple case foldings, and \w's WordCharacters
// gains the runes that fold into [A-Za-z0-9_]: ſ (U+017F) and K (U+212A). So
// \w, \W, \b and \B see ſ as a word character, /\p{Lu}/ui matches "a", and
// \P{Lu} differs by mode: under u it is the complement matched by folding (it
// matches "A", whose orbit holds "a"), under v the complement of the folded
// set (it does not). Without u or v the legacy Canonicalize never maps a
// non-ASCII rune to ASCII, so none of this applies; those rows guard it.
func TestCaseFolding_Escapes(t *testing.T) {
	cases := []struct {
		pattern    string
		flags      flags.Flags
		input      string
		start, end int // byte offsets of the match, or -1
	}{
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\w`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`\w`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\w`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\w`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\w`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\W`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\W`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`\w+`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\w+`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\W+`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "s", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "k", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "a", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "1", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 1},
		{`\b`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 0},
		{`\b`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`\B`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`\B`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`\B`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\B`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 0},
		{`\B`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 1, 1},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u017fx", 2, 2},
		{`\B`, flags.Unicode | flags.IgnoreCase, "\u212ax", 3, 3},
		{`\B`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 1, 1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 3, 4},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u017fx", 2, 3},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "\u212ax", 3, 4},
		{`x\b`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\bx`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\w]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\W]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[^\w]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[^\W]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\W\d]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\p{Lu}`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\P{Lu}`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[^\p{Lu}]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[^\P{Lu}]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\p{Ll}+`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 4},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\P{Ll}+`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\p{Script=Latin}`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\P{Script=Greek}`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\P{Ll}\d]`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 3, 4},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u017fx", 2, 3},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "\u212ax", 3, 4},
		{`(?<=\w)x`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u017fx", 2, 3},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "\u212ax", 3, 4},
		{`(?<!\W)x`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\w*x`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u017f", 0, 2},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u212a", 0, 3},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "s", 0, 1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "k", 0, 1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "a", 0, 1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u0130", -1, -1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u0131", -1, -1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "1", 0, 1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u017fx", 0, 3},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "\u212ax", 0, 4},
		{`(?:\w|y)+$`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u017f", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u212a", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "s", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "k", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "a", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u0130", 0, 2},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u0131", 0, 2},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u03a3", 0, 2},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u03c3", 0, 2},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u03c2", 0, 2},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "1", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, " \u017f ", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u017fx", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "\u212ax", -1, -1},
		{`^\W*$`, flags.Unicode | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\w`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\W`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\w+`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\W+`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 1},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 0},
		{`\b`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 0},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 1, 1},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 2, 2},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 3, 3},
		{`\B`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 1, 1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 3, 4},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 2, 3},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 3, 4},
		{`x\b`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\bx`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\w]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\W]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[^\w]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[^\W]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\W\d]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\p{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\P{Lu}`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[^\p{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`[^\P{Lu}]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\p{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`\P{Ll}+`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 1, 3},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\p{Script=Latin}`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 2},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 3},
		{`\P{Script=Greek}`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\P{Ll}\d]`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 3, 4},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 2, 3},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 3, 4},
		{`(?<=\w)x`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 1},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 2, 3},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 3, 4},
		{`(?<!\W)x`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 3},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 4},
		{`\w*x`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", 0, 2},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", 0, 3},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "s", 0, 1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "k", 0, 1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "a", 0, 1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", -1, -1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", -1, -1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "1", 0, 1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", 0, 4},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", 0, 3},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", 0, 4},
		{`(?:\w|y)+$`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", 0, 7},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u017f", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u212a", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "s", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "k", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "a", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u0130", 0, 2},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u0131", 0, 2},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u03a3", 0, 2},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u03c3", 0, 2},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u03c2", 0, 2},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "1", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, " \u017f ", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "x\u017fx", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u017fx", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "\u212ax", -1, -1},
		{`^\W*$`, flags.UnicodeSets | flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\w`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\w`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\w`, flags.IgnoreCase, "s", 0, 1},
		{`\w`, flags.IgnoreCase, "k", 0, 1},
		{`\w`, flags.IgnoreCase, "a", 0, 1},
		{`\w`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\w`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\w`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w`, flags.IgnoreCase, "1", 0, 1},
		{`\w`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\w`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\w`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`\w`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`\w`, flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\W`, flags.IgnoreCase, "\u017f", 0, 2},
		{`\W`, flags.IgnoreCase, "\u212a", 0, 3},
		{`\W`, flags.IgnoreCase, "s", -1, -1},
		{`\W`, flags.IgnoreCase, "k", -1, -1},
		{`\W`, flags.IgnoreCase, "a", -1, -1},
		{`\W`, flags.IgnoreCase, "\u0130", 0, 2},
		{`\W`, flags.IgnoreCase, "\u0131", 0, 2},
		{`\W`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`\W`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`\W`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`\W`, flags.IgnoreCase, "1", -1, -1},
		{`\W`, flags.IgnoreCase, " \u017f ", 0, 1},
		{`\W`, flags.IgnoreCase, "x\u017fx", 1, 3},
		{`\W`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`\W`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`\W`, flags.IgnoreCase, "a\u212a\u017fx", 1, 4},
		{`\w+`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\w+`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\w+`, flags.IgnoreCase, "s", 0, 1},
		{`\w+`, flags.IgnoreCase, "k", 0, 1},
		{`\w+`, flags.IgnoreCase, "a", 0, 1},
		{`\w+`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\w+`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\w+`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w+`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w+`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w+`, flags.IgnoreCase, "1", 0, 1},
		{`\w+`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\w+`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\w+`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`\w+`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`\w+`, flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\W+`, flags.IgnoreCase, "\u017f", 0, 2},
		{`\W+`, flags.IgnoreCase, "\u212a", 0, 3},
		{`\W+`, flags.IgnoreCase, "s", -1, -1},
		{`\W+`, flags.IgnoreCase, "k", -1, -1},
		{`\W+`, flags.IgnoreCase, "a", -1, -1},
		{`\W+`, flags.IgnoreCase, "\u0130", 0, 2},
		{`\W+`, flags.IgnoreCase, "\u0131", 0, 2},
		{`\W+`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`\W+`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`\W+`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`\W+`, flags.IgnoreCase, "1", -1, -1},
		{`\W+`, flags.IgnoreCase, " \u017f ", 0, 4},
		{`\W+`, flags.IgnoreCase, "x\u017fx", 1, 3},
		{`\W+`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`\W+`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`\W+`, flags.IgnoreCase, "a\u212a\u017fx", 1, 6},
		{`\b`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\b`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\b`, flags.IgnoreCase, "s", 0, 0},
		{`\b`, flags.IgnoreCase, "k", 0, 0},
		{`\b`, flags.IgnoreCase, "a", 0, 0},
		{`\b`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\b`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\b`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\b`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\b`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\b`, flags.IgnoreCase, "1", 0, 0},
		{`\b`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\b`, flags.IgnoreCase, "x\u017fx", 0, 0},
		{`\b`, flags.IgnoreCase, "\u017fx", 2, 2},
		{`\b`, flags.IgnoreCase, "\u212ax", 3, 3},
		{`\b`, flags.IgnoreCase, "a\u212a\u017fx", 0, 0},
		{`\B`, flags.IgnoreCase, "\u017f", 0, 0},
		{`\B`, flags.IgnoreCase, "\u212a", 0, 0},
		{`\B`, flags.IgnoreCase, "s", -1, -1},
		{`\B`, flags.IgnoreCase, "k", -1, -1},
		{`\B`, flags.IgnoreCase, "a", -1, -1},
		{`\B`, flags.IgnoreCase, "\u0130", 0, 0},
		{`\B`, flags.IgnoreCase, "\u0131", 0, 0},
		{`\B`, flags.IgnoreCase, "\u03a3", 0, 0},
		{`\B`, flags.IgnoreCase, "\u03c3", 0, 0},
		{`\B`, flags.IgnoreCase, "\u03c2", 0, 0},
		{`\B`, flags.IgnoreCase, "1", -1, -1},
		{`\B`, flags.IgnoreCase, " \u017f ", 0, 0},
		{`\B`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\B`, flags.IgnoreCase, "\u017fx", 0, 0},
		{`\B`, flags.IgnoreCase, "\u212ax", 0, 0},
		{`\B`, flags.IgnoreCase, "a\u212a\u017fx", 4, 4},
		{`x\b`, flags.IgnoreCase, "\u017f", -1, -1},
		{`x\b`, flags.IgnoreCase, "\u212a", -1, -1},
		{`x\b`, flags.IgnoreCase, "s", -1, -1},
		{`x\b`, flags.IgnoreCase, "k", -1, -1},
		{`x\b`, flags.IgnoreCase, "a", -1, -1},
		{`x\b`, flags.IgnoreCase, "\u0130", -1, -1},
		{`x\b`, flags.IgnoreCase, "\u0131", -1, -1},
		{`x\b`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`x\b`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`x\b`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`x\b`, flags.IgnoreCase, "1", -1, -1},
		{`x\b`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`x\b`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`x\b`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`x\b`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`x\b`, flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`\bx`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\bx`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\bx`, flags.IgnoreCase, "s", -1, -1},
		{`\bx`, flags.IgnoreCase, "k", -1, -1},
		{`\bx`, flags.IgnoreCase, "a", -1, -1},
		{`\bx`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\bx`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\bx`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\bx`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\bx`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\bx`, flags.IgnoreCase, "1", -1, -1},
		{`\bx`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\bx`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\bx`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`\bx`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`\bx`, flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`[\w]`, flags.IgnoreCase, "\u017f", -1, -1},
		{`[\w]`, flags.IgnoreCase, "\u212a", -1, -1},
		{`[\w]`, flags.IgnoreCase, "s", 0, 1},
		{`[\w]`, flags.IgnoreCase, "k", 0, 1},
		{`[\w]`, flags.IgnoreCase, "a", 0, 1},
		{`[\w]`, flags.IgnoreCase, "\u0130", -1, -1},
		{`[\w]`, flags.IgnoreCase, "\u0131", -1, -1},
		{`[\w]`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\w]`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\w]`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\w]`, flags.IgnoreCase, "1", 0, 1},
		{`[\w]`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`[\w]`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[\w]`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`[\w]`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`[\w]`, flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\W]`, flags.IgnoreCase, "\u017f", 0, 2},
		{`[\W]`, flags.IgnoreCase, "\u212a", 0, 3},
		{`[\W]`, flags.IgnoreCase, "s", -1, -1},
		{`[\W]`, flags.IgnoreCase, "k", -1, -1},
		{`[\W]`, flags.IgnoreCase, "a", -1, -1},
		{`[\W]`, flags.IgnoreCase, "\u0130", 0, 2},
		{`[\W]`, flags.IgnoreCase, "\u0131", 0, 2},
		{`[\W]`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\W]`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\W]`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\W]`, flags.IgnoreCase, "1", -1, -1},
		{`[\W]`, flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\W]`, flags.IgnoreCase, "x\u017fx", 1, 3},
		{`[\W]`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\W]`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\W]`, flags.IgnoreCase, "a\u212a\u017fx", 1, 4},
		{`[^\w]`, flags.IgnoreCase, "\u017f", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "\u212a", 0, 3},
		{`[^\w]`, flags.IgnoreCase, "s", -1, -1},
		{`[^\w]`, flags.IgnoreCase, "k", -1, -1},
		{`[^\w]`, flags.IgnoreCase, "a", -1, -1},
		{`[^\w]`, flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "1", -1, -1},
		{`[^\w]`, flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\w]`, flags.IgnoreCase, "x\u017fx", 1, 3},
		{`[^\w]`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`[^\w]`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`[^\w]`, flags.IgnoreCase, "a\u212a\u017fx", 1, 4},
		{`[^\W]`, flags.IgnoreCase, "\u017f", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "\u212a", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "s", 0, 1},
		{`[^\W]`, flags.IgnoreCase, "k", 0, 1},
		{`[^\W]`, flags.IgnoreCase, "a", 0, 1},
		{`[^\W]`, flags.IgnoreCase, "\u0130", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "\u0131", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "1", 0, 1},
		{`[^\W]`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`[^\W]`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[^\W]`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`[^\W]`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`[^\W]`, flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[\W\d]`, flags.IgnoreCase, "\u017f", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "\u212a", 0, 3},
		{`[\W\d]`, flags.IgnoreCase, "s", -1, -1},
		{`[\W\d]`, flags.IgnoreCase, "k", -1, -1},
		{`[\W\d]`, flags.IgnoreCase, "a", -1, -1},
		{`[\W\d]`, flags.IgnoreCase, "\u0130", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "\u0131", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "1", 0, 1},
		{`[\W\d]`, flags.IgnoreCase, " \u017f ", 0, 1},
		{`[\W\d]`, flags.IgnoreCase, "x\u017fx", 1, 3},
		{`[\W\d]`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`[\W\d]`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`[\W\d]`, flags.IgnoreCase, "a\u212a\u017fx", 1, 4},
		{`\p{Lu}`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "s", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "k", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "a", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "1", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`\p{Lu}`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "s", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "k", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "a", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "1", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`\P{Lu}`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u017f", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u212a", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "s", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "k", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "a", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u0130", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u0131", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "1", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\p{Lu}]`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u017f", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u212a", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "s", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "k", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "a", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u0130", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u0131", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "1", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\P{Lu}]`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u017f", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u212a", 0, 3},
		{`[^\p{Lu}]`, flags.IgnoreCase, "s", 0, 1},
		{`[^\p{Lu}]`, flags.IgnoreCase, "k", 0, 1},
		{`[^\p{Lu}]`, flags.IgnoreCase, "a", 0, 1},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "1", 0, 1},
		{`[^\p{Lu}]`, flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\p{Lu}]`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`[^\p{Lu}]`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`[^\p{Lu}]`, flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u017f", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u212a", 0, 3},
		{`[^\P{Lu}]`, flags.IgnoreCase, "s", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, "k", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, "a", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u0130", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u0131", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "1", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, " \u017f ", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u017fx", 0, 2},
		{`[^\P{Lu}]`, flags.IgnoreCase, "\u212ax", 0, 3},
		{`[^\P{Lu}]`, flags.IgnoreCase, "a\u212a\u017fx", 0, 1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "s", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "k", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "a", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "1", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`\p{Ll}+`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "s", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "k", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "a", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "1", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`\P{Ll}+`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "s", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "k", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "a", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "1", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`\p{Script=Latin}`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "s", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "k", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "a", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "1", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`\P{Script=Greek}`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u017f", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u212a", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "s", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "k", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "a", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u0130", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u0131", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "1", 0, 1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`[\P{Ll}\d]`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u017f", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u212a", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "s", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "k", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "a", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u0130", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u0131", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "1", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`(?<=\w)x`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u017f", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u212a", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "s", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "k", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "a", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u0130", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u0131", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "1", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`(?<!\W)x`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u017f", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u212a", -1, -1},
		{`\w*x`, flags.IgnoreCase, "s", -1, -1},
		{`\w*x`, flags.IgnoreCase, "k", -1, -1},
		{`\w*x`, flags.IgnoreCase, "a", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u0130", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u0131", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`\w*x`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`\w*x`, flags.IgnoreCase, "1", -1, -1},
		{`\w*x`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`\w*x`, flags.IgnoreCase, "x\u017fx", 0, 1},
		{`\w*x`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`\w*x`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`\w*x`, flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u017f", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u212a", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "s", 0, 1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "k", 0, 1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "a", 0, 1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u0130", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u0131", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u03a3", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u03c3", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u03c2", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "1", 0, 1},
		{`(?:\w|y)+$`, flags.IgnoreCase, " \u017f ", -1, -1},
		{`(?:\w|y)+$`, flags.IgnoreCase, "x\u017fx", 3, 4},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u017fx", 2, 3},
		{`(?:\w|y)+$`, flags.IgnoreCase, "\u212ax", 3, 4},
		{`(?:\w|y)+$`, flags.IgnoreCase, "a\u212a\u017fx", 6, 7},
		{`^\W*$`, flags.IgnoreCase, "\u017f", 0, 2},
		{`^\W*$`, flags.IgnoreCase, "\u212a", 0, 3},
		{`^\W*$`, flags.IgnoreCase, "s", -1, -1},
		{`^\W*$`, flags.IgnoreCase, "k", -1, -1},
		{`^\W*$`, flags.IgnoreCase, "a", -1, -1},
		{`^\W*$`, flags.IgnoreCase, "\u0130", 0, 2},
		{`^\W*$`, flags.IgnoreCase, "\u0131", 0, 2},
		{`^\W*$`, flags.IgnoreCase, "\u03a3", 0, 2},
		{`^\W*$`, flags.IgnoreCase, "\u03c3", 0, 2},
		{`^\W*$`, flags.IgnoreCase, "\u03c2", 0, 2},
		{`^\W*$`, flags.IgnoreCase, "1", -1, -1},
		{`^\W*$`, flags.IgnoreCase, " \u017f ", 0, 4},
		{`^\W*$`, flags.IgnoreCase, "x\u017fx", -1, -1},
		{`^\W*$`, flags.IgnoreCase, "\u017fx", -1, -1},
		{`^\W*$`, flags.IgnoreCase, "\u212ax", -1, -1},
		{`^\W*$`, flags.IgnoreCase, "a\u212a\u017fx", -1, -1},
	}
	for _, tc := range cases {
		re, err := ecma262.Compile(tc.pattern, tc.flags)
		if err != nil {
			t.Errorf("/%s/ (flags %v): %v", tc.pattern, tc.flags, err)
			continue
		}
		loc, err := re.FindStringIndexErr(tc.input)
		start, end := -1, -1
		if loc != nil {
			start, end = loc[0], loc[1]
		}
		if err != nil || start != tc.start || end != tc.end {
			t.Errorf("/%s/ (flags %v) on %q: got [%d,%d] %v, want [%d,%d]", tc.pattern, tc.flags, tc.input, start, end, err, tc.start, tc.end)
		}
	}
}
