// Command genemoji generates vm/emoji_strings.go, the members of the Unicode
// properties of strings that the v flag exposes (\p{RGI_Emoji} and its six
// constituents), from the UTS #51 data files:
//
//	curl -fsSO https://www.unicode.org/Public/17.0.0/emoji/emoji-sequences.txt
//	curl -fsSO https://www.unicode.org/Public/17.0.0/emoji/emoji-zwj-sequences.txt
//	go run ./tools/genemoji -seq emoji-sequences.txt -zwj emoji-zwj-sequences.txt -out vm/emoji_strings.go
//
// Fetch the files from the numbered directory matching unicode.Version, not
// from /Public/emoji/latest: that moves ahead of both Go and the JavaScript
// engines, and properties of strings must come from the same Unicode version
// as the character properties they are combined with. The generator refuses
// data whose declared version does not match.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// The properties each file must define. RGI_Emoji, their union, is derived at
// run time rather than stored.
var properties = []struct{ name, file string }{
	{"Basic_Emoji", "seq"},
	{"Emoji_Keycap_Sequence", "seq"},
	{"RGI_Emoji_Flag_Sequence", "seq"},
	{"RGI_Emoji_Modifier_Sequence", "seq"},
	{"RGI_Emoji_Tag_Sequence", "seq"},
	{"RGI_Emoji_ZWJ_Sequence", "zwj"},
}

func main() {
	seqPath := flag.String("seq", "", "path to emoji-sequences.txt")
	zwjPath := flag.String("zwj", "", "path to emoji-zwj-sequences.txt")
	out := flag.String("out", "vm/emoji_strings.go", "output file")
	flag.Parse()
	if *seqPath == "" || *zwjPath == "" {
		log.Fatal("usage: genemoji -seq emoji-sequences.txt -zwj emoji-zwj-sequences.txt [-out file]")
	}

	// unicode.Version is "major.minor.patch"; emoji data declares "major.minor".
	want := unicode.Version[:strings.LastIndexByte(unicode.Version, '.')]
	files := map[string]map[string][]string{}
	for key, path := range map[string]string{"seq": *seqPath, "zwj": *zwjPath} {
		version, props, err := readSequences(path)
		if err != nil {
			log.Fatalf("%s: %v", path, err)
		}
		if version != want {
			log.Fatalf("%s: declares Emoji %q, but Go's unicode package is %s; fetch the %s data", path, version, unicode.Version, want)
		}
		files[key] = props
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/genemoji from the Emoji %s data files; DO NOT EDIT.\n\n", want)
	b.WriteString("package vm\n\n")
	b.WriteString("// emojiVersion is the Emoji version of propertiesOfStrings. It must equal the\n")
	b.WriteString("// major.minor of unicode.Version, so that properties of strings and character\n")
	b.WriteString("// properties describe the same Unicode.\n")
	fmt.Fprintf(&b, "const emojiVersion = %q\n\n", want)
	b.WriteString("// propertiesOfStrings maps each property of strings except RGI_Emoji (the\n")
	b.WriteString("// union of the others) to its members, in data file order.\n")
	b.WriteString("var propertiesOfStrings = map[string][]string{\n")
	for _, p := range properties {
		members := files[p.file][p.name]
		if len(members) == 0 {
			log.Fatalf("property %s not found in its data file", p.name)
		}
		fmt.Fprintf(&b, "\t%q: {\n", p.name)
		for _, m := range members {
			fmt.Fprintf(&b, "\t\t%s,\n", strconv.QuoteToASCII(m))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}

// readSequences parses a UTS #51 sequence file: lines of
//
//	code points ; type field ; description # comment
//
// where the code points are a space-separated sequence, or a range lo..hi
// denoting that many single-code-point members.
func readSequences(path string) (version string, props map[string][]string, err error) {
	f, err := os.Open(path)
	if err != nil {
		return "", nil, err
	}
	defer f.Close()

	props = map[string][]string{}
	sc := bufio.NewScanner(f)
	for n := 1; sc.Scan(); n++ {
		line := sc.Text()
		if v, ok := strings.CutPrefix(line, "# Version:"); ok && version == "" {
			version = strings.TrimSpace(v)
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 {
			return "", nil, fmt.Errorf("line %d: expected code points ; property", n)
		}
		name := strings.TrimSpace(fields[1])
		cps := strings.TrimSpace(fields[0])
		if lo, hi, ok := strings.Cut(cps, ".."); ok {
			a, err1 := parseCodePoint(lo)
			z, err2 := parseCodePoint(hi)
			if err1 != nil || err2 != nil || a > z {
				return "", nil, fmt.Errorf("line %d: bad range %q", n, cps)
			}
			for r := a; r <= z; r++ {
				props[name] = append(props[name], string(r))
			}
			continue
		}
		var s strings.Builder
		for _, h := range strings.Fields(cps) {
			r, err := parseCodePoint(h)
			if err != nil {
				return "", nil, fmt.Errorf("line %d: %v", n, err)
			}
			s.WriteRune(r)
		}
		props[name] = append(props[name], s.String())
	}
	if err := sc.Err(); err != nil {
		return "", nil, err
	}
	if version == "" {
		return "", nil, fmt.Errorf("no '# Version:' header")
	}
	return version, props, nil
}

func parseCodePoint(h string) (rune, error) {
	v, err := strconv.ParseUint(strings.TrimSpace(h), 16, 32)
	if err != nil || v > unicode.MaxRune || v >= 0xD800 && v <= 0xDFFF {
		return 0, fmt.Errorf("bad code point %q", h)
	}
	return rune(v), nil
}
