// Command genpropnames generates vm/property_names.go, every spelling
// ECMA-262 accepts for a General_Category or Script value in \p{...}: the
// short name, the long name and any other alias, exactly as
// PropertyValueAliases.txt lists them. ECMA-262 matches these names exactly,
// with no loose matching of case, spaces or underscores.
//
//	curl -fsSO https://www.unicode.org/Public/17.0.0/ucd/PropertyValueAliases.txt
//	go run ./tools/genpropnames -in PropertyValueAliases.txt
//
// The file must be from the Unicode version of Go's unicode package; the
// generator refuses any other.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"unicode"
)

func main() {
	in := flag.String("in", "", "path to PropertyValueAliases.txt")
	out := flag.String("out", "vm/property_names.go", "output file")
	flag.Parse()
	if *in == "" {
		log.Fatal("usage: genpropnames -in PropertyValueAliases.txt [-out file]")
	}
	f, err := os.Open(*in)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	version := ""
	gc := map[string]string{} // spelling -> short name (unicode.Categories key)
	sc := map[string]string{} // spelling -> long name (unicode.Scripts key)
	sc2 := map[string]bool{}  // scripts Go has no table for
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := s.Text()
		if v, ok := strings.CutPrefix(line, "# PropertyValueAliases-"); ok && version == "" {
			version = strings.TrimSuffix(strings.TrimSpace(v), ".txt")
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		for i := range fields {
			fields[i] = strings.TrimSpace(fields[i])
		}
		if len(fields) < 3 {
			continue
		}
		switch fields[0] {
		case "gc":
			short := fields[1]
			if unicode.Categories[short] == nil {
				log.Fatalf("General_Category %s has no table in Go's unicode package", short)
			}
			for _, name := range fields[1:] {
				gc[name] = short
			}
		case "sc":
			long := fields[2]
			// Unknown (Zzzz) is every code point in no other script, which
			// the vm computes rather than looks up.
			if unicode.Scripts[long] == nil && long != "Unknown" {
				// Katakana_Or_Hiragana has no code points of its own and no
				// Go table; JavaScript engines reject it too.
				sc2[long] = true
				continue
			}
			for _, name := range fields[1:] {
				sc[name] = long
			}
		}
	}
	if err := s.Err(); err != nil {
		log.Fatal(err)
	}
	if version != unicode.Version {
		log.Fatalf("%s is Unicode %q, but Go's unicode package is %s", *in, version, unicode.Version)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/genpropnames from PropertyValueAliases-%s.txt; DO NOT EDIT.\n\n", version)
	b.WriteString("package vm\n\n")
	b.WriteString("// propertyNamesVersion is the Unicode version of these names.\n")
	fmt.Fprintf(&b, "const propertyNamesVersion = %q\n\n", version)
	b.WriteString("// generalCategoryNames maps every spelling of a General_Category value to\n")
	b.WriteString("// its short name, which keys unicode.Categories.\n")
	writeMap(&b, "generalCategoryNames", gc)
	b.WriteString("\n// scriptNames maps every spelling of a Script value to its long name, which\n")
	b.WriteString("// keys unicode.Scripts (except Unknown, which is computed).")
	if len(sc2) > 0 {
		b.WriteString("\n// Scripts without a Go table are omitted:")
		for _, n := range sortedKeys(sc2) {
			b.WriteString(" " + n)
		}
		b.WriteString(".")
	}
	b.WriteString("\n")
	writeMap(&b, "scriptNames", sc)
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

func writeMap(b *strings.Builder, name string, m map[string]string) {
	fmt.Fprintf(b, "var %s = map[string]string{\n", name)
	for _, k := range sortedKeys(m) {
		fmt.Fprintf(b, "\t%q: %q,\n", k, m[k])
	}
	b.WriteString("}\n")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
