// Command genpropnames generates the Unicode property data Go's unicode
// package lacks, from the UCD files of its Unicode version:
//
//   - vm/property_names.go: every spelling ECMA-262 accepts for a
//     General_Category or Script value in \p{...} (the short name, the long
//     name and any other alias, exactly as PropertyValueAliases.txt lists
//     them; ECMA-262 matches these names exactly).
//   - vm/ucd_props.go: the code points of the binary properties Go has no
//     table for (or only an approximation of), and each script's
//     Script_Extensions.
//
// Fetch the files from https://www.unicode.org/Public/17.0.0/ucd/ and run
//
//	go run ./tools/genpropnames -in PropertyValueAliases.txt \
//	    -core DerivedCoreProperties.txt -norm DerivedNormalizationProps.txt \
//	    -binary DerivedBinaryProperties.txt -scx ScriptExtensions.txt
//
// Every file must be from the Unicode version of Go's unicode package; the
// generator refuses any other.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

func main() {
	in := flag.String("in", "", "path to PropertyValueAliases.txt")
	out := flag.String("out", "vm/property_names.go", "output file for the names")
	core := flag.String("core", "", "path to DerivedCoreProperties.txt")
	norm := flag.String("norm", "", "path to DerivedNormalizationProps.txt")
	binary := flag.String("binary", "", "path to extracted/DerivedBinaryProperties.txt")
	scx := flag.String("scx", "", "path to ScriptExtensions.txt")
	tablesOut := flag.String("tablesout", "vm/ucd_props.go", "output file for the tables")
	flag.Parse()
	if *in == "" || *core == "" || *norm == "" || *binary == "" || *scx == "" {
		log.Fatal("usage: genpropnames -in PropertyValueAliases.txt -core DerivedCoreProperties.txt -norm DerivedNormalizationProps.txt -binary DerivedBinaryProperties.txt -scx ScriptExtensions.txt")
	}
	f, err := os.Open(*in)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	version := ""
	gc := map[string]string{} // spelling -> short name (unicode.Categories key)
	sc := map[string]string{} // spelling -> long name (unicode.Scripts key)
	sc2 := map[string]bool{}  // scripts Go has no table for
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := s.Text()
		if v, ok := strings.CutPrefix(line, "# PropertyValueAliases-"); ok && version == "" {
			version = strings.TrimSuffix(strings.TrimSpace(v), ".txt")
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		for i := range fields {
			fields[i] = strings.TrimSpace(fields[i])
		}
		if len(fields) < 3 {
			continue
		}
		switch fields[0] {
		case "gc":
			short := fields[1]
			if unicode.Categories[short] == nil {
				log.Fatalf("General_Category %s has no table in Go's unicode package", short)
			}
			for _, name := range fields[1:] {
				gc[name] = short
			}
		case "sc":
			long := fields[2]
			// Unknown (Zzzz) is every code point in no other script, which
			// the vm computes rather than looks up.
			if unicode.Scripts[long] == nil && long != "Unknown" {
				// Katakana_Or_Hiragana has no code points of its own and no
				// Go table; JavaScript engines reject it too.
				sc2[long] = true
				continue
			}
			for _, name := range fields[1:] {
				sc[name] = long
			}
		}
	}
	if err := s.Err(); err != nil {
		log.Fatal(err)
	}
	if version != unicode.Version {
		log.Fatalf("%s is Unicode %q, but Go's unicode package is %s", *in, version, unicode.Version)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/genpropnames from PropertyValueAliases-%s.txt; DO NOT EDIT.\n\n", version)
	b.WriteString("package vm\n\n")
	b.WriteString("// propertyNamesVersion is the Unicode version of these names.\n")
	fmt.Fprintf(&b, "const propertyNamesVersion = %q\n\n", version)
	b.WriteString("// generalCategoryNames maps every spelling of a General_Category value to\n")
	b.WriteString("// its short name, which keys unicode.Categories.\n")
	writeMap(&b, "generalCategoryNames", gc)
	b.WriteString("\n// scriptNames maps every spelling of a Script value to its long name, which\n")
	b.WriteString("// keys unicode.Scripts (except Unknown, which is computed).")
	if len(sc2) > 0 {
		b.WriteString("\n// Scripts without a Go table are omitted:")
		for _, n := range sortedKeys(sc2) {
			b.WriteString(" " + n)
		}
		b.WriteString(".")
	}
	b.WriteString("\n")
	writeMap(&b, "scriptNames", sc)
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}

	writeTables(*tablesOut, sc, []propertySource{
		{*core, []string{
			"Case_Ignorable", "Changes_When_Casefolded", "Changes_When_Casemapped",
			"Changes_When_Titlecased", "Changes_When_Uppercased",
			"Default_Ignorable_Code_Point", "Grapheme_Base",
			"ID_Continue", "ID_Start", "XID_Continue", "XID_Start",
		}},
		{*norm, []string{"Changes_When_NFKC_Casefolded"}},
		{*binary, []string{"Bidi_Mirrored"}},
	}, *scx)
}

type propertySource struct {
	path  string
	props []string
}

// writeTables writes the binary property tables and Script_Extensions.
// scriptNames maps script spellings (ScriptExtensions.txt uses the short
// codes) to the long names the vm keys scripts by.
func writeTables(path string, scriptNames map[string]string, sources []propertySource, scxPath string) {
	props := map[string][]rune{}
	var names []string
	for _, src := range sources {
		for _, l := range readUCD(src.path) {
			// Binary properties have two fields; enumerated ones (InCB, the
			// normalization quick checks) have more and are skipped.
			if len(l.fields) == 1 {
				props[l.fields[0]] = append(props[l.fields[0]], l.cps...)
			}
		}
		for _, p := range src.props {
			if len(props[p]) == 0 {
				log.Fatalf("%s: no code points for %s", src.path, p)
			}
			names = append(names, p)
		}
	}

	scx := map[string][]rune{}
	var listed []rune
	for _, l := range readUCD(scxPath) {
		listed = append(listed, l.cps...)
		for _, code := range strings.Fields(l.fields[0]) {
			long, ok := scriptNames[code]
			if !ok {
				log.Fatalf("%s: unknown script %s", scxPath, code)
			}
			scx[long] = append(scx[long], l.cps...)
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by tools/genpropnames; DO NOT EDIT.\n\n")
	b.WriteString("package vm\n\n")
	b.WriteString("// ucdProperties maps the binary properties Go's unicode package has no\n")
	b.WriteString("// exact table for to their code points, as sorted, disjoint, non-adjacent\n")
	b.WriteString("// ranges. Its version is propertyNamesVersion.\n")
	b.WriteString("var ucdProperties = map[string][]RuneRange{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q: %s,\n", n, ranges(props[n]))
	}
	b.WriteString("}\n\n")
	b.WriteString("// scriptExtensions maps each script's long name to the code points whose\n")
	b.WriteString("// Script_Extensions lists it. A code point not in scriptExtensionsListed has\n")
	b.WriteString("// Script_Extensions equal to its Script.\n")
	b.WriteString("var scriptExtensions = map[string][]RuneRange{\n")
	for _, n := range sortedKeys(scx) {
		fmt.Fprintf(&b, "\t%q: %s,\n", n, ranges(scx[n]))
	}
	b.WriteString("}\n\n")
	b.WriteString("// scriptExtensionsListed holds every code point ScriptExtensions.txt lists.\n")
	fmt.Fprintf(&b, "var scriptExtensionsListed = []RuneRange%s\n", ranges(listed))
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// ranges formats code points as a RuneRange literal of sorted, merged ranges.
func ranges(cps []rune) string {
	cps = slices.Clone(cps)
	slices.Sort(cps)
	cps = slices.Compact(cps)
	var b strings.Builder
	b.WriteString("{")
	for i := 0; i < len(cps); {
		j := i
		for j+1 < len(cps) && cps[j+1] == cps[j]+1 {
			j++
		}
		fmt.Fprintf(&b, "{0x%04X, 0x%04X}, ", cps[i], cps[j])
		i = j + 1
	}
	b.WriteString("}")
	return b.String()
}

type ucdLine struct {
	cps    []rune
	fields []string // the fields after the code points
}

// readUCD reads a UCD data file of "code points ; field ; ... # comment"
// lines, checking that its header declares Go's Unicode version.
func readUCD(path string) []ucdLine {
	f, err := os.Open(path)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	var out []ucdLine
	versionOK := false
	s := bufio.NewScanner(f)
	for n := 1; s.Scan(); n++ {
		line := s.Text()
		if n == 1 {
			versionOK = strings.HasSuffix(strings.TrimSpace(line), "-"+unicode.Version+".txt")
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 {
			continue
		}
		for i := range fields {
			fields[i] = strings.TrimSpace(fields[i])
		}
		lo, hi, isRange := strings.Cut(fields[0], "..")
		if !isRange {
			hi = lo
		}
		a, err1 := strconv.ParseUint(lo, 16, 32)
		z, err2 := strconv.ParseUint(hi, 16, 32)
		if err1 != nil || err2 != nil || a > z {
			log.Fatalf("%s:%d: bad code points %q", path, n, fields[0])
		}
		var cps []rune
		for c := a; c <= z; c++ {
			cps = append(cps, rune(c))
		}
		out = append(out, ucdLine{cps: cps, fields: fields[1:]})
	}
	if err := s.Err(); err != nil {
		log.Fatal(err)
	}
	if !versionOK {
		log.Fatalf("%s: first line does not declare Unicode %s", path, unicode.Version)
	}
	return out
}

func writeMap(b *strings.Builder, name string, m map[string]string) {
	fmt.Fprintf(b, "var %s = map[string]string{\n", name)
	for _, k := range sortedKeys(m) {
		fmt.Fprintf(b, "\t%q: %q,\n", k, m[k])
	}
	b.WriteString("}\n")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
